traffic_dbt:
  outputs:
    dev:
      type: postgres
      threads: 10
      host: 127.0.0.1
      port: 5434
      user: airflow
      pass: airflow
      dbname: airflow
      schema: traffic_raw

    prod:
      type: postgres
      threads: 10
      host: 127.0.0.1
      port: 5434
      user: airflow
      pass: airflow
      dbname: traffic_raw
      schema: public

  target: dev
